
spring:       

    # HTTP ENCODING

    http:

        encoding.charset: UTF-8

        encoding.enable: true

        encoding.force: true

   

    datasource:

        validation-query: SELECT 1

        test-on-borrow: true

        

    mvc:

        view:

            prefix: /WEB-INF/jsp/

            suffix: .jsp    
